apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-service
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      nodePort: 31883
