apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ingress-key
  name: {{ .Chart.Name }}-ingress
  namespace: emissary
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: {{ .Values.global.mosquitto.tcpExternalPort }}
    protocol: TCP
    targetPort: {{ .Values.global.mosquitto.tcpExternalPort }}
  - name: tcp
    port: {{ .Values.global.mosquitto.wsExternalPort }}
    protocol: TCP
    targetPort: {{ .Values.global.mosquitto.wsExternalPort }}
  selector:
    profile: main
    service: ambassador
  sessionAffinity: None
  type: LoadBalancer
