apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  selector:
    app: vxfuel
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1884
    - name: mqtt-tls
      protocol: TCP
      port: 8883
      targetPort: 8883
    - name: mqtt-ws
      protocol: TCP
      port: 9101
      targetPort: 9101
      
      