apiVersion: v1
kind: PersistentVolume
metadata:
  name: vxfuel-persist-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /opt/vxfuel/persist
  
