apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.appName }}-persist-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /opt/{{ .Values.global.appName }}/persist
  
