apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-simulator
  labels:
    app: efs-simulator
  annotations:
    linkerd.io/inject: "disabled"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-simulator
  template:
    metadata:
      labels:
        app: efs-simulator
    spec:
      imagePullSecrets:
        - name: edge-docker-pull-secret      
      containers:
        - name: efs-simulator
          image: us-east1-docker.pkg.dev/ret-edge-pltf-infra/workloads/efs-simulator:1.1.4
          ports:
          - containerPort: 8000
          - containerPort: 1883
          - containerPort: 9001