apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-simulator
  labels:
    app: efs-simulator
  annotations:
    linkerd.io/inject: "disabled"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-simulator
  template:
    metadata:
      labels:
        app: efs-simulator
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secrets.name }}   
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
      containers:
        - name: efs-simulator
          image: "{{ .Values.global.repository }}/efs-simulator:{{ .Values.global.imageVersion }}"
          volumeMounts:
          - name: config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          ports:
          - containerPort: {{ .Values.global.efsSimulator.httpExternalPort }}
          - containerPort: {{ .Values.global.mosquitto.tcpExternalPort }}
          - containerPort: {{ .Values.global.mosquitto.wsExternalPort }}