apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: mqtt-server
  namespace: emissary
spec:
  port: 1883
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: opaque
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: mqtt-server-auth
  namespace: emissary
spec:
  client:
    unauthenticated: true
  server:
    name: mqtt-server
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: mqtt-ws-server
  namespace: emissary
spec:
  port: 9001
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: mqtt-ws-server-auth
  namespace: emissary
spec:
  client:
    unauthenticated: true
  server:
    name: mqtt-ws-server
