apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{ .Chart.Name }}-mqtt-server
  namespace: emissary
spec:
  port: {{ .Values.global.mosquitto.tcpExternalPort }}
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: opaque
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{ .Chart.Name }}-mqtt-server-auth
  namespace: emissary
spec:
  client:
    unauthenticated: true
  server:
    name: {{ .Chart.Name }}-mqtt-server
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{ .Chart.Name }}-mqtt-ws-server
  namespace: emissary
spec:
  port: {{ .Values.global.mosquitto.wsExternalPort }}
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{ .Chart.Name }}-mqtt-ws-server-auth
  namespace: emissary
spec:
  client:
    unauthenticated: true
  server:
    name: {{ .Chart.Name }}-mqtt-ws-server
