apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ingress-key
  name: efs-simulator-ingress
  namespace: emissary
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: tcp
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    profile: main
    service: ambassador
  sessionAffinity: None
  type: LoadBalancer
