apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: {{ .Chart.Name }}-mqtt
  namespace: efs-simulator
spec:
  port: {{ .Values.global.mosquitto.tcpExternalPort }}
  service: efs-simulator.efs-simulator:{{ .Values.global.mosquitto.tcpExternalPort }}
---
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: {{ .Chart.Name }}-mqtt-ws
  namespace: efs-simulator
spec:
  port: {{ .Values.global.mosquitto.wsExternalPort }}
  service: efs-simulator.efs-simulator:{{ .Values.global.mosquitto.wsExternalPort }}
