apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /web/
        backend:
          service:
            name: efs-simulator
            port:
              number: {{ .Values.global.efsSimulator.httpInternalPort }}

