apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efs-simulator-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: efs-simulator
            port:
              number: 8000