apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: efs-simulator-server
spec:
  port: 8000
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: efs-simulator-server-auth
spec:
  client:
    unauthenticated: true
  server:
    name: efs-simulator-server
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: efs-simulator-mqtt
spec:
  port: 183
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: TCP
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: efs-simulator-mqtt-auth
spec:
  client:
    unauthenticated: true
  server:
    name: efs-simulator-mqtt
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: efs-simulator-mqttws
spec:
  port: 9001
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: efs-simulator-mqttws-auth
spec:
  client:
    unauthenticated: true
  server:
    name: efs-simulator-mqttws