apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{ .Chart.Name }}-server
spec:
  port: {{ .Values.global.efsSimulator.httpExternalPort }}
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{ .Chart.Name }}-server-auth
spec:
  client:
    unauthenticated: true
  server:
    name: {{ .Chart.Name }}-server
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{ .Chart.Name }}-mqtt
spec:
  port: {{ .Values.global.mosquitto.tcpExternalPort }}
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: opaque
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{ .Chart.Name }}-mqtt-auth
spec:
  client:
    unauthenticated: true
  server:
    name: {{ .Chart.Name }}-mqtt
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{ .Chart.Name }}-mqttws
spec:
  port: {{ .Values.global.mosquitto.wsExternalPort }}
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{ .Chart.Name }}-mqttws-auth
spec:
  client:
    unauthenticated: true
  server:
    name: {{ .Chart.Name }}-mqttws