apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: efs-simulator
  namespace: efs-simulator
spec:
  hostname: "efs-simulator.store.ncr.corp"
  prefix: "/web/"
  service: efs-simulator:80
  
---

apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: listener-efs-simulator-mosquitto
  namespace: efs-simulator
spec:
  hostBinding:
    namespace:
      from: ALL
  port: 9001
  protocolStack:
  - TLS
  - TCP
  securityModel: INSECURE

---
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: efs-simulator-mqtt
  namespace: efs-simulator
spec:
  host: efs-simulator-mqtt.store.ncr.corp
  port: 9001
  service: efs-simulator:9001
