apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: efs-simulator
  namespace: efs-simulator
spec:
  hostname: "efs-simulator.store.ncr.corp"
  prefix: "/web/"
  service: efs-simulator:80
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: efs-simulator-mosquitto-ws
  namespace: efs-simulator
spec:
  hostname: "efs-simulator.store.ncr.corp"
  prefix: "/mqtt/"
  service: efs-simulator:9001
  allow_upgrade:
    - websocket
