apiVersion: v1
kind: Service
metadata:
  name: efs-simulator
spec:
  selector:
    app: efs-simulator
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.global.efsSimulator.httpInternalPort }}
      targetPort: {{ .Values.global.efsSimulator.httpExternalPort }}
    - name: mqttws
      protocol: TCP
      port: {{ .Values.global.mosquitto.wsExternalPort }}
      targetPort: {{ .Values.global.mosquitto.wsExternalPort }}
    - name: mqtt
      protocol: TCP
      port: {{ .Values.global.mosquitto.tcpExternalPort }}
      targetPort: {{ .Values.global.mosquitto.tcpExternalPort }}      
