apiVersion: v2
name: tdmsender-mosquitto
appVersion: "1.0"
description: Installation of TDM sender and mosquitto 1.0 
version: 0.1.2
type: application
namespace: "my-namespace"
dependencies:
  - name: "mosquitto"
    version: "0.1.0"
  - name: "tdmsender"
    version: "0.1.0"